# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/vivado_project/MIPS_CPU/MIPS_CPU.srcs/sources_1/ip/iromIP/iromIP.xci
# IP: The module: 'iromIP' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_project/MIPS_CPU/MIPS_CPU.srcs/sources_1/ip/iromIP/iromIP_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'iromIP'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/vivado_project/MIPS_CPU/MIPS_CPU.srcs/sources_1/ip/iromIP/iromIP.xci
# IP: The module: 'iromIP' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_project/MIPS_CPU/MIPS_CPU.srcs/sources_1/ip/iromIP/iromIP_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'iromIP'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
